In [14]:
import pandas as pd
pockemon = pd.read_csv ('../pokemon.csv')
combats = pd.read_csv ('../combats.csv')
test = pd.read_csv ('../tests.csv')
pockemon.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [15]:
combats.head()

   First_pokemon  Second_pokemon  Winner
0            266             298     298
1            702             701     701
2            191             668     668
3            237             683     683
4            151             231     151

In [16]:
test.head()

   First_pokemon  Second_pokemon
0            129             117
1            660             211
2            706             115
3            195             618
4             27             656

In [19]:
pockemon.isnull().sum()

#               0
Name            1
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [20]:
pockemon['Type 2'] = pockemon['Type 2'].fillna("None")

In [21]:
pockemon = pockemon.dropna(subset=['Name'])

In [22]:
pockemon.isnull().sum()

#             0
Name          0
Type 1        0
Type 2        0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
dtype: int64

In [24]:
pockemon = pockemon.drop_duplicates()

In [25]:
pockemon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 799 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           799 non-null    int64
 1   Name        799 non-null    object
 2   Type 1      799 non-null    object
 3   Type 2      799 non-null    object
 4   HP          799 non-null    int64
 5   Attack      799 non-null    int64
 6   Defense     799 non-null    int64
 7   Sp. Atk     799 non-null    int64
 8   Sp. Def     799 non-null    int64
 9   Speed       799 non-null    int64
 10  Generation  799 non-null    int64
 11  Legendary   799 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 66.3+ KB